'use strict';
/**
 * Writes testdata/tokens/ -- the golden token streams the Go parser is built
 * against.
 *
 *   make tokens        # regenerate (needs Node)
 *
 * WHY THIS EXISTS SEPARATELY FROM make conformance
 *
 * `make conformance` replays behaviour: pattern in, boolean out. It cannot move
 * until the scanner, the emitter AND the matcher all work, so during the months
 * the parser is being written it reads 0% and says nothing about progress. This
 * fixture gives the parser its own pass/fail number, available from the first
 * token it emits.
 *
 * It is a DIFFERENT KIND OF EVIDENCE from testdata/original, and the difference
 * is worth stating plainly. testdata/original is recorded from upstream's own
 * unmodified suite; nobody chose its contents, which is what makes the parity
 * number worth quoting. This file is recorded from upstream's parser over the
 * patterns that suite happened to use -- the observation is just as real, but
 * the pattern list is inherited rather than independent, and every record is
 * internal state that DECISIONS.md §6 explicitly excludes from parity. So it is
 * reported separately and never folded into the headline figure.
 *
 * WHY IT IS COMMITTED
 *
 * 1.1MB, versus ~40MB for the fingerprint artifact, which is why that one stays
 * in the gitignored testdata/probes/. Committing keeps `go test` working with no
 * Node installed, the same property testdata/original is committed for.
 *
 * Regenerate only when the upstream pin moves. `make verify-original` is the
 * receipt that the tree this was recorded from is unmodified.
 */

const fs = require('fs');
const path = require('path');
const corpus = require('../probes/lib/corpus');

const parse = corpus.parseModule();
const OUT_DIR = path.join(corpus.ROOT, 'testdata', 'tokens');

// `prev` is a back-pointer to the previous token. Serialising it would recurse
// through the whole stream at every element; the Go side rebuilds adjacency
// from position, which is what `prev` is for.
const strip = t => {
  const o = {};
  for (const k of Object.keys(t)) if (k !== 'prev') o[k] = t[k];
  return o;
};

const pats = corpus.patterns().sort();
const out = [];
const fastpath = { none: 0, top: 0, inline: 0 };
const fieldTypes = new Map();
const typeCounts = new Map();
let threw = 0, diverges = 0, backtrack = 0;

for (const pattern of pats) {
  let st;
  try {
    // fastpaths:false is what picomatch.parse itself passes (picomatch.js:212),
    // so this is the full scanner every time -- the thing the Go parser is.
    st = parse(pattern, { fastpaths: false });
  } catch (e) {
    // A pattern the reference parser rejects is not a token assertion. The Go
    // parser's error behaviour is pinned by testdata/original instead, which
    // records the message and the constructor name.
    threw++;
    continue;
  }

  const fp = corpus.fastpathOf(pattern);
  const div = fp !== 'none' && corpus.fastpathDiverges(pattern);
  fastpath[fp]++;
  if (div) diverges++;
  if (st.backtrack === true) backtrack++;

  for (const t of st.tokens) {
    typeCounts.set(t.type, (typeCounts.get(t.type) || 0) + 1);
    for (const k of Object.keys(t)) {
      if (k === 'prev') continue;
      if (!fieldTypes.has(k)) fieldTypes.set(k, new Set());
      fieldTypes.get(k).add(typeof t[k]);
    }
  }

  out.push(JSON.stringify({
    pattern,
    consumed: st.consumed,
    output: st.output,
    negated: st.negated,
    backtrack: st.backtrack,
    // Which parser makeRe would really have used, and whether it agreed. The Go
    // gate stratifies its score on these rather than filtering: matching these
    // tokens is always the right answer for a full-scanner parser, but where a
    // fastpath ran and diverged it no longer settles what makeRe compiled.
    fastpath: fp,
    fastpathDiverges: div,
    tokens: st.tokens.map(strip),
  }));
}

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, 'cases.jsonl'), out.join('\n') + '\n');

const summary = {
  _comment: 'Generated by tools/tokens/generate.js from the vendored upstream at tests/original. Golden token streams for the Go parser; reported separately from conformance parity, never folded into it. Do not hand-edit.',
  upstream: JSON.parse(fs.readFileSync(path.join(corpus.UPSTREAM_DIR, 'MANIFEST.json'), 'utf8')).upstream,
  generatedBy: 'tools/tokens/generate.js',
  cases: {
    total: out.length,
    threw,
    tokens: [...typeCounts.values()].reduce((a, b) => a + b, 0),
    backtrack,
  },
  // Which parser makeRe would have used for each pattern. Eligibility is not
  // use: 382 patterns start '.' or '*' and so reach parse.fastpaths(), but it
  // returns falsy for most and picomatch.js:316 falls through to the scanner.
  fastpath: { ...fastpath, diverges },
  tokenTypes: Object.fromEntries([...typeCounts].sort((a, b) => b[1] - a[1])),
  tokenFields: Object.fromEntries([...fieldTypes].map(([k, v]) => [k, [...v].sort().join('|')])),
};
fs.writeFileSync(path.join(OUT_DIR, 'summary.json'), JSON.stringify(summary, null, 2) + '\n');

console.log('wrote testdata/tokens/cases.jsonl  (%d patterns, %d threw, %d tokens)',
  out.length, threw, summary.cases.tokens);
console.log('  full scanner %d   parse.fastpaths() %d   inline %d   (of those, %d diverge)',
  fastpath.none, fastpath.top, fastpath.inline, diverges);
console.log('  %d token types, %d fields', typeCounts.size, fieldTypes.size);
